server:
  port: 8082
  servlet:
    context-path: /note
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
spring:
  application:
    name: share-buy-note