server:
  port: 8081
  servlet:
    context-path: /account
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
spring:
  application:
    name: share-buy-account
  datasource:
    url: jdbc:mysql://localhost:3306/share-buy-account?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: hutengqi1228.?
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 1000
      connection-test-query: select 1
      idle-timeout: 60000
      connection-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      show-sql: true
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: share_buy_account_producer
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
