server:
  port: 8081
  servlet:
    context-path: /account
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
spring:
  application:
    name: share-buy-account
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: share_buy_account_producer
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
